# Generated by Django 4.1.3 on 2022-12-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='C:/Users/Shemar/OneDrive/Personal Projects/Portfolio Website/portfolio/website/static'),
        ),
    ]
